name: new_version
description: Check if your user has the most recent version of your Flutter app.
version: 0.3.1
homepage: https://github.com/timtraversy/new_version

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^5.0.0
  http: ^1.0.0
  html: ^0.15.4
  url_launcher: ^6.1.14
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
